server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.addr@
    gateway:
      routes:
        - id: route1_qq #配置了一个 id 为 route1_qq 的URI代理规则
          uri: http://www.qq.com
          predicates:
            - Path=/test/
          #当访问地址http://localhost:8000/test/时，
          #会路由到上游地址http://www.qq.com/test/
